#
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityhub
  namespace: edc-v
  labels:
    app: identityhub
    type: edcv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityhub
  template:
    metadata:
      labels:
        app: identityhub
        platform: edcv
    spec:
      containers:
        - name: identityhub
          image: ghcr.io/metaform/jad/identity-hub:0.15.0-SNAPSHOT
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ih-config
          ports:
            - containerPort: 7082
              name: creds-port
            - containerPort: 1044
              name: debug
            - containerPort: 7081
              name: identity-api
            - containerPort: 7083
              name: did
            - containerPort: 7080
              name: web

          livenessProbe:
            httpGet:
              path: /api/check/liveness
              port: 7080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 120
          readinessProbe:
            httpGet:
              path: /api/check/readiness
              port: 7080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 120
          startupProbe:
            httpGet:
              path: /api/check/startup
              port: 7080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 120

---
apiVersion: v1
kind: Service
metadata:
  name: identityhub
  namespace: edc-v
spec:
  type: NodePort
  selector:
    app: identityhub
  ports:
    - port: 7082
      targetPort: 7082
      name: creds-port
    - port: 1044
      targetPort: 1044
      name: debug
    - port: 7081
      targetPort: 7081
      name: identity-api
    - port: 7083
      targetPort: 7083
      name: did
    - port: 7084
      targetPort: 7084
      name: sts

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identityhub
  namespace: edc-v
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /cs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: identityhub
                port:
                  number: 7081

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identityhub-did
  namespace: edc-v
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(/|&)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: identityhub
                port:
                  number: 7083
