apiVersion: v1
kind: ConfigMap
metadata:
  name: ih-config
  namespace: edc-v
data:
  edc.hostname: "identityhub.edc-v.svc.cluster.local"
  edc.iam.credentia.revocation.mimetype: "application/json"
  edc.iam.did.web.use.https: "false"
  edc.ih.iam.publickey.alias: "publickey-alias"
  edc.ih.api.superuser.key: "c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo="
  web.http.port: "7080"
  web.http.path: "/api"
  web.http.identity.port: "7081"
  web.http.identity.path: "/api/identity"
  web.http.identity.auth.key: "password"
  web.http.credentials.port: "7082"
  web.http.credentials.path: "/api/credentials"
  web.http.did.port: "7083"
  web.http.did.path: "/"
  web.http.sts.port: "7084"
  web.http.sts.path: "/api/sts"
  JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044"

  edc.vault.hashicorp.url: "http://vault.edc-v.svc.cluster.local:8200"
  edc.vault.hashicorp.token: "root"

  edc.datasource.default.url: "jdbc:postgresql://postgres.edc-v.svc.cluster.local:5432/identityhub"
  edc.datasource.default.user: "ih"
  edc.datasource.default.password: "ih"
  edc.sql.schema.autocreate: "true"
  edc.iam.accesstoken.jti.validation: "true"
  # grace period for credential expiry, 3600*24 = 1 day
  edc.iam.credential.renewal.graceperiod: "86400"