#
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

resources:
  - edcv-namespace.yaml
  - postgres.yaml
  - nats.yaml
  - keycloak.yaml
  - vault.yaml
  - controlplane-config.yaml
  - controlplane.yaml
  - dataplane-config.yaml
  - dataplane.yaml
  - issuerservice-config.yaml
  - issuerservice.yaml
  - identityhub-config.yaml
  - identityhub.yaml

