#
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

resources:
  - base/edcv-namespace.yaml
  - base/postgres.yaml
  - base/nats.yaml
  - base/keycloak.yaml
  - base/vault.yaml
  - apps/controlplane-config.yaml
  - apps/controlplane.yaml
  - apps/dataplane-config.yaml
  - apps/dataplane.yaml
  - apps/issuerservice-config.yaml
  - apps/issuerservice.yaml
  - apps/identityhub-config.yaml
  - apps/identityhub.yaml

