#
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataplane
  namespace: edc-v
  labels:
    app: dataplane
    type: edcv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataplane
  template:
    metadata:
      labels:
        app: dataplane
        platform: edcv
        type: edcv-app
    spec:
      containers:
        - name: dataplane
          image: ghcr.io/metaform/jad/dataplane:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dataplane-config
          ports:
            - containerPort: 11002
              name: public-port
            - containerPort: 1044
              name: debug-port
            - containerPort: 8083
              name: control-port
            - containerPort: 8186
              name: certs-port
            - containerPort: 8080
              name: health-port
          livenessProbe:
            httpGet:
              path: /api/check/liveness
              port: 8080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/check/readiness
              port: 8080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 30
          startupProbe:
            httpGet:
              path: /api/check/startup
              port: 8080
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: dataplane
  namespace: edc-v
spec:
  type: NodePort
  selector:
    app: dataplane
  ports:
    - name: health
      port: 8080
      targetPort: 8080
    - name: control
      port: 8083
      targetPort: 8083
    - name: certs
      port: 8186
      targetPort: 8186
    - name: public
      port: 11002
      targetPort: 11002

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dataplane
  namespace: edc-v
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /dp/public(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dataplane
                port:
                  number: 11002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dataplane-control
  namespace: edc-v
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /app/internal(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dataplane
                port:
                  number: 8083

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dataplane-certs-control
  namespace: edc-v
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /app/public(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dataplane
                port:
                  number: 8186