#
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfm-provision-manager
  namespace: edc-v
  labels:
    app: provision-manager
    platform: edcv
    type: edcv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provision-manager
  template:
    metadata:
      labels:
        app: provision-manager
        platform: edcv
        type: edcv-app
    spec:
      containers:
        - name: provision-manager
          image: ghcr.io/metaform/connector-fabric-manager/pmanager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/appname
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: pm-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: provision-manager
  namespace: edc-v
spec:
  selector:
    app: provision-manager
  ports:
    - port: 8080
      targetPort: 8080
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: provision-manager
  namespace: edc-v
spec:
  rules:
    - host: pm.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: provision-manager
                port:
                  number: 8080
