#
# Copyright (c) 2026 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redline-config
  namespace: edc-v
  labels:
    app: redline
data:
  SPRING_PROFILES_ACTIVE: "dev-pg"
  DATABASE_URL: "jdbc:postgresql://postgres.edc-v.svc.cluster.local:5432/redlinedb"
  DATABASE_USERNAME: "redline"
  DATABASE_PASSWORD: "redline"

  # urls for external services
  KEYCLOAK_TOKENURL: "http://keycloak.edc-v.svc.cluster.local:8080/realms/edcv/protocol/openid-connect/token"
  CONTROLPLANE_URL: "http://controlplane.edc-v.svc.cluster.local:8081/api/mgmt"
  DATAPLANE_URL: "http://dataplane.edc-v.svc.cluster.local:8186/api/data"
  DATAPLANE_INTERNAL_URL: "http://dataplane.edc-v.svc.cluster.local:8083/api/control"
  VAULT_URL: "http://vault.edc-v.svc.cluster.local:8200"
  IDENTITYHUB_URL: "http://identityhub.edc-v.svc.cluster.local:7081/identities"
  TENANT-MANAGER_URL: "http://tenant-manager.edc-v.svc.cluster.local:8080"
  CORS_ALLOWED_ORIGIN: "http://ui.localhost"