#
# Copyright (c) 2025 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: edc-v
  labels:
    platform: edcv
    type: edcv-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        platform: edcv
        type: edcv-infra
    spec:
      containers:
        - name: postgres
          image: postgres:17.7-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "controlplane"
            - name: POSTGRES_USER
              value: "cp"
            - name: POSTGRES_PASSWORD
              value: "cp"
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: edc-v
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: edc-v
data:
  init.sql: |
    CREATE DATABASE identityhub;
    CREATE USER ih WITH PASSWORD 'ih';
    GRANT ALL PRIVILEGES ON DATABASE identityhub TO ih;
    \c identityhub
    GRANT ALL ON SCHEMA public TO ih;
    
    CREATE DATABASE issuerservice;
    CREATE USER issuer WITH PASSWORD 'issuer';
    GRANT ALL PRIVILEGES ON DATABASE issuerservice TO issuer;
    \c issuerservice
    GRANT ALL ON SCHEMA public TO issuer;
    
    CREATE DATABASE dataplane;
    CREATE USER dp WITH PASSWORD 'dp';
    GRANT ALL PRIVILEGES ON DATABASE dataplane TO dp;
    \c dataplane
    GRANT ALL ON SCHEMA public TO dp;
    
    CREATE DATABASE keycloak;
    CREATE USER kc WITH PASSWORD 'kc';
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO kc;
    \c keycloak
    GRANT ALL ON SCHEMA public TO kc;
    
    CREATE DATABASE keycloak_fe;
    CREATE USER kc_fe WITH PASSWORD 'kc_fe';
    GRANT ALL PRIVILEGES ON DATABASE keycloak_fe TO kc_fe;
    \c keycloak_fe
    GRANT ALL ON SCHEMA public TO kc_fe;
    
    CREATE DATABASE cfm;
    CREATE USER cfm WITH PASSWORD 'cfm';
    GRANT ALL PRIVILEGES ON DATABASE cfm TO cfm;
    \c cfm
    GRANT ALL ON SCHEMA public TO cfm;

    CREATE DATABASE redlinedb;
    CREATE USER redline WITH PASSWORD 'redline';
    GRANT ALL PRIVILEGES ON DATABASE redlinedb TO redline;
    \c redlinedb
    GRANT ALL ON SCHEMA public TO redline;